# This is a golangci-lint configuration file
# Documentation: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosimple

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
